### PR TITLE
Added user Agent to the call

### PR DESCRIPTION
**Pull request by cloudbooster**
This will provide details specific to the caller. I tested this on ubuntu. Let me know if this is fine and I can merge the doc update from your side.

### CODE REVIEW

**Comment by cloudbooster** [comment]
@keirans  can you please take a look

**Comment by keirans** [comment]
This is awesome, thanks for doing this.
I'll try and get this tested on the other primary platforms that I know the module is being used on (RHEL and Windows) and then merge accordingly.

Cheers,

K

**Comment by cloudbooster** [comment]
@keirans Thanks ! btw I have merged your doc update.

**Comment by keirans** [comment]
Haven't forgotten about this, just a bit lower on the priority list. I'll get it in by Sunday however.
Just need to get some time to test. 
I'll probably bundle a ARM Template with the next update that contains a set of virtual machines we can test on to make this a bit easier.

**Comment by keirans** [comment]
I've tested this all OK on the following versions of Puppet Agent releases.
* Puppet Enterprise 2018.1.
  * Windows 2016 - 5.5.1
  * RHEL 7 - 5.5.1 

I expect any versions to be using a version of Ruby from the last 5+ years should also be fine.

I'll be updating the package alongside some other minor changes shortly.

Thanks,

K

**Comment by keirans** [comment]
Merged in via https://github.com/keirans/azuremetadata/pull/20.

Thanks for your help :)

**Pull request merged**
