### PR TITLE
Updated to latest API version and parsed tags as structured facts

### PR DESCRIPTION
**Pull request by steve-hawkins**
This PR covers upgrading to the new API version which includes tags

I've parsed the tags returned from the API into structured facts

Added some validation

### CODE REVIEW

**Comment by keirans** [comment]
Hi @steve-hawkins !
This is amazing, thanks a bunch for this.

The code looks good, can I ask that you please update your PR with the following just to keep the documentation in step with the code, specifcally these 2 components.
* An update to the README.md to include the version of the API that the new version is targeting (Under limitations)
* And update to the README.md to contain an example of the facter output (Windows or Linux output is fine either way) as the structure / schema has changed between the versions.

Once done, I'll merge and tag a new release and get it up on the forge.

Thanks again, really appreciate someone else contributing !

**Comment by steve-hawkins** [comment]
Hi @keirans 

No worries, much easier to keep one public module updated rather than maintain our own

README all updated, I went for 0.1.2 which I tagged on our fork until the PR is merged

**Comment by keirans** [comment]
Thanks again for this, I'll be publishing the new version on the forge later today.

**Comment by keirans** [comment]
Published :)

https://forge.puppet.com/keirans/azuremetadata/0.1.2/readme

**Pull request merged**
