### PR TITLE
Fix confine statement.

### PR DESCRIPTION
**Pull request by pillarsdotnet**
The syntax of the `confine` statement was incompatible with my puppet version.

### CODE REVIEW

**Comment by keirans** [comment]
Hey @pillarsdotnet ,
Can I ask that you please raise an issue that details:
- Puppet Enterprise version (if applicable)
- Puppet version
- Ruby version
- Facter version
- OS Version
- Detailed error message and failure output
- Any other relevant information (method of installation, replication steps, etc)

This will let me understand the issue more and track it accordingly.

Right now, it looks like I've got a set of users using a range of different configurations, and I want to see if I can capture as much data as I can, and make sure I'm not breaking things for other users.

It might be worth me putting some version specific logic into some of this code where applicable or similar.

Thanks!

K

**Comment by pillarsdotnet** [comment]
Puppet version is the same as last time -- puppet gem version 4.5.3, ruby version 1.8.3.  O/S was Windows 2008R2 but I don't believe the problem is windows-specific.

When I get a chance, I'll produce a minimal manifest that illustrates the problem.

**Comment by keirans** [comment]
Thanks for the information.
I'll see if I can spend a bit of time over this weekend resolving this for you.

Cheers!

K

**Comment by keirans** [comment]
Thanks for your feedback, I've merged fixes for this and the metadata version we use into master.
I'll be publishing a new release shortly.

Cheers,

K

**Pull request closed without merging**
